apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-tools-for-java/hello-spring-boot
    jibMaven: {}

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
